// Pure contract checks; IDB commit and UI behavior run in library_harness.html.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const block=name=>{const start=html.indexOf(`// ${name}_BEGIN`),end=html.indexOf(`// ${name}_END`);assert.ok(start>=0&&end>start,`${name} missing`);return html.slice(start,end);};
const {libraryRecordValid,libraryProgress,coverHeader}=new Function(block('GENERIC_INGEST')+'\n'+block('LIBRARY')+'\nreturn {libraryRecordValid,libraryProgress,coverHeader};')();
const record=()=>({version:1,identity:'generic-v1:txt:'+'a'.repeat(64),format:'txt',reimportStable:true,importedAt:1,lastReadAt:2,position:{seg:1},cover:null,doc:{title:'Synthetic',audio:'',chapters:[],segments:[{id:0,start:0,end:1,text:'one two'},{id:1,start:1,end:2,text:'three'},{id:2,start:2,end:3,text:'four'}]}});
test('library progress measures words strictly before the saved segment, never completion',()=>{const r=record();assert.equal(libraryProgress(r),50);r.position.seg=0;assert.equal(libraryProgress(r),0);r.position.seg=2;assert.equal(libraryProgress(r),75);r.doc.segments[0].text='word '.repeat(1000);assert.equal(libraryProgress(r),99);});
test('stored library records validate documents and finite dates without poisoning healthy rows',()=>{assert.ok(libraryRecordValid(record()));for(const mutate of [r=>r.version=2,r=>r.identity='',r=>r.importedAt=NaN,r=>r.lastReadAt=Infinity,r=>r.doc.segments=[],r=>r.doc.title='',r=>r.format='html']){const r=record();mutate(r);assert.ok(!libraryRecordValid(r));}});
test('cover header admission refuses SVG, wrong types, truncation, and oversized raster headers',()=>{assert.ok(!coverHeader(new TextEncoder().encode('<svg/>'),'image/svg+xml'));for(const type of ['image/png','image/jpeg','image/webp'])assert.ok(!coverHeader(Uint8Array.of(1,2,3),type));const png=new Uint8Array(33);png.set([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82]);const dv=new DataView(png.buffer);dv.setUint32(16,100000);dv.setUint32(20,100000);assert.ok(!coverHeader(png,'image/png'));assert.ok(!coverHeader(png,'image/jpeg'));});

const pngHeader=(width,height,length=45)=>{const b=new Uint8Array(length),v=new DataView(b.buffer);b.set([137,80,78,71,13,10,26,10]);v.setUint32(8,13);b.set(new TextEncoder().encode('IHDR'),12);v.setUint32(16,width);v.setUint32(20,height);if(length>45){v.setUint32(33,length-57);b.set(new TextEncoder().encode('IDAT'),37);}b.set(new TextEncoder().encode('IEND'),length-8);return b;};
test('cover admission enforces exact byte and pixel ceilings before decode',()=>{assert.deepEqual(coverHeader(pngHeader(4000,4000),'image/png'),{width:4000,height:4000});assert.equal(coverHeader(pngHeader(4000,4001),'image/png'),null);assert.deepEqual(coverHeader(pngHeader(1,1,5242880),'image/png'),{width:1,height:1});assert.equal(coverHeader(pngHeader(1,1,5242881),'image/png'),null);assert.equal(coverHeader(pngHeader(0,1),'image/png'),null);});
test('WebP extended canvas cannot disguise an oversized lossless frame',()=>{const b=new Uint8Array(44),v=new DataView(b.buffer),str=(offset,text)=>b.set(new TextEncoder().encode(text),offset);str(0,'RIFF');v.setUint32(4,36,true);str(8,'WEBP');str(12,'VP8X');v.setUint32(16,10,true);str(30,'VP8L');v.setUint32(34,5,true);b[38]=47;v.setUint32(39,0x0fffffff,true);assert.equal(coverHeader(b,'image/webp'),null);});
