#!/usr/bin/env python3
"""
list_chapters.py — read the Wandering Inn Table of Contents and emit a chapter-URL
list ready for fetch_text.py. Works for ANY volume or ANY audiobook "Book" — past
or future — because it reads the live TOC each run.

The web serial is grouped into **Volumes**; the published audiobooks are **Books**
that cover a *sub-range* of a Volume. The TOC lists every chapter as a link in
reading order, so the reliable way to get a Book is to **slice the ordered list
between its first and last chapter** — which also picks up the Interludes that sit
between numbered chapters (a plain "6.33–6.47" number filter would drop them).

Usage:
  python3 list_chapters.py                          # list all Volumes + chapter counts
  python3 list_chapters.py --volume 6 --list        # show a Volume's chapters
  python3 list_chapters.py --volume 6 --out vol6_chapters.txt
  python3 list_chapters.py --from 6.33 --to 6.47 --out book12_chapters.txt
      # an audiobook Book = a slice; interludes between the endpoints are included

Then feed the list to the fetcher:
  python3 fetch_text.py --url-file book12_chapters.txt --out book12

--from / --to match against the URL slug: "6.33" matches the slug "6-33-e", "6.47"
matches "6-47-e", and everything between (incl. interludes) comes along. Selectors
are inclusive.

Dependencies:  pip3 install requests beautifulsoup4
"""
import argparse, re, sys

TOC_URL = "https://wanderinginn.com/table-of-contents/"
UA = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                   "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}
CHAP = re.compile(r"wanderinginn\.com/\d{4}/\d{2}/\d{2}/([^/?#]+)/?", re.I)
VOL  = re.compile(r"\bVolume\s+(\d+)", re.I)

def fetch(url):
    import requests
    r = requests.get(url, headers=UA, timeout=30)
    r.raise_for_status()
    return r.text

def parse_toc(html):
    """Walk the TOC in document order; tag each chapter link with its Volume."""
    from bs4 import BeautifulSoup
    soup = BeautifulSoup(html, "html.parser")
    body = soup.select_one("div.entry-content") or soup.select_one("article") or soup
    chapters, vol, seen = [], None, set()
    for node in body.descendants:
        name = getattr(node, "name", None)
        if name in ("h1", "h2", "h3", "h4"):
            m = VOL.search(node.get_text(" ", strip=True))
            if m:
                vol = int(m.group(1))
        elif name == "a" and node.get("href"):
            m = CHAP.search(node["href"])
            if not m:
                continue
            url = node["href"]
            if url in seen:
                continue
            seen.add(url)
            chapters.append({"volume": vol, "label": node.get_text(" ", strip=True),
                             "url": url, "slug": m.group(1).lower()})
    return chapters

def norm(sel):
    return sel.strip().lower().replace(" ", "-").replace(".", "-").strip("-")

def match_idx(chapters, sel, last=False):
    n = norm(sel)
    idxs = [i for i, c in enumerate(chapters)
            if c["slug"] == n or c["slug"].startswith(n + "-")]
    if not idxs:
        sys.exit(f"No chapter matched {sel!r} (normalized {n!r}). Try --list to see slugs.")
    if len(idxs) > 1 and not last:
        print(f"  ! {sel!r} matched {len(idxs)} chapters; using the first "
              f"({chapters[idxs[0]]['slug']}).", file=sys.stderr)
    return idxs[-1] if last else idxs[0]

def write_list(chapters, out, header):
    lines = [f"# {header}", f"# {len(chapters)} chapters, generated by list_chapters.py", ""]
    lines += [c["url"] for c in chapters]
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out}: {len(chapters)} chapter URLs.")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--volume", type=int, help="restrict to one Volume number")
    ap.add_argument("--from", dest="frm", help="first chapter of a range (e.g. 6.33)")
    ap.add_argument("--to", help="last chapter of a range (e.g. 6.47)")
    ap.add_argument("--list", action="store_true", help="print chapters/volumes instead of URLs")
    ap.add_argument("--out", help="write the URL list here (for fetch_text.py --url-file)")
    ap.add_argument("--toc-url", default=TOC_URL, help="override the Table of Contents URL")
    a = ap.parse_args()

    chapters = parse_toc(fetch(a.toc_url))
    if not chapters:
        sys.exit("No chapters parsed — TOC markup may have changed (adjust the selector).")

    # overview when nothing is selected
    if not a.volume and not a.frm and not a.to:
        vols = {}
        for c in chapters:
            vols.setdefault(c["volume"], 0)
            vols[c["volume"]] += 1
        print(f"{len(chapters)} chapters across {len([v for v in vols if v])} volumes "
              f"(reading the live TOC):")
        for v in sorted(k for k in vols if k is not None):
            print(f"  Volume {v}: {vols[v]} chapters")
        if None in vols:
            print(f"  (ungrouped: {vols[None]})")
        print("\nPick a slice:  --volume N   or   --from <chap> --to <chap>   (add --out FILE)")
        return

    sel = chapters
    header = "The Wandering Inn — chapters"
    if a.volume:
        sel = [c for c in sel if c["volume"] == a.volume]
        header = f"The Wandering Inn — Volume {a.volume}"
        if not sel:
            sys.exit(f"No chapters found for Volume {a.volume}.")
    if a.frm or a.to:
        lo = match_idx(chapters, a.frm) if a.frm else 0
        hi = match_idx(chapters, a.to, last=True) if a.to else len(chapters) - 1
        if lo > hi:
            sys.exit(f"--from ({a.frm}) comes after --to ({a.to}) in reading order.")
        sel = chapters[lo:hi + 1]
        header = f"The Wandering Inn — {a.frm or 'start'} … {a.to or 'end'}"

    if a.list or not a.out:
        for c in sel:
            tag = f"[V{c['volume']}] " if c["volume"] else ""
            print(f"  {tag}{c['label']:<34}  {c['url']}")
        print(f"\n{len(sel)} chapters.")
    if a.out:
        write_list(sel, a.out, header)

if __name__ == "__main__":
    main()
